f = open('mahesh.txt','w')
f.write("Hello cutie")
f = open('mahesh.txt','a')
f.write(" cse-c")
f = open('mahesh.txt','r')
print(f.read())
f.seek(5)
pos = f.tell()
print(pos)
f.read(5)
pos = f.tell()
print(pos)
f.close()
